// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBqKcglJxXZUdG8UOuSLtFOgEk5Dp8S_o',
    appId: '1:781892459777:web:0a2aa3be5b3ea681520f00',
    messagingSenderId: '781892459777',
    projectId: 'fir-tutorial-8f618',
    authDomain: 'fir-tutorial-8f618.firebaseapp.com',
    storageBucket: 'fir-tutorial-8f618.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZJoCRJrNZHAjojkdry4DigdJOkdcDlv4',
    appId: '1:781892459777:android:de9ba537f69d154d520f00',
    messagingSenderId: '781892459777',
    projectId: 'fir-tutorial-8f618',
    storageBucket: 'fir-tutorial-8f618.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsOw2oOBmD7LMNySnkyhCUosgse8Ygi3E',
    appId: '1:781892459777:ios:0ebc48310392c952520f00',
    messagingSenderId: '781892459777',
    projectId: 'fir-tutorial-8f618',
    storageBucket: 'fir-tutorial-8f618.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
